apiVersion: v1
kind: Service
metadata:
  creationTimestamp: "2025-08-20T00:04:03Z"
  labels:
    app: flask-app-deploy
  name: flask-app-svc
  namespace: apps
  resourceVersion: "82224"
  uid: 8ad93c6d-dbd9-45ca-850f-1cd1b2e17e71
spec:
  clusterIP: 10.105.99.230
  clusterIPs:
  - 10.105.99.230
  externalTrafficPolicy: Cluster
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - nodePort: 30986
    port: 5000
    protocol: TCP
    targetPort: 5000
  selector:
    app: flask-app-deploy
  sessionAffinity: None
  type: NodePort
status:
  loadBalancer: {}
