apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: flask-app-deploy
  name: flask-app-deploy
  namespace: apps
spec:
  replicas: 1
  selector:
    matchLabels:
      app: flask-app-deploy
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: flask-app-deploy
    spec:
      containers:
      - image: sohaash/simple_flask_app:v0.4
        name: flask-app 
        ports:
        - containerPort: 5000
        resources: {}
status: {}
