apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: mariadb-service
  name: mariadb-service
  namespace: database-server
spec:
  ports:
  - name: 3306-3306
    port: 3306
    protocol: TCP
    targetPort: 3306
  selector:
    run: maria-db
  type: ClusterIP
status:
  loadBalancer: {}
