global: {}

route:
  group_by: ['alertname']
  group_wait: 30s
  group_interval: 5m
  repeat_interval: 3h
  receiver: 'telegram'

receivers:
   - name: 'telegram'
     telegram_configs:
     - bot_token_file: /etc/alertmanager/telegram_token
       chat_id: -4942810868

