apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: mariadb-db
  name: mariadb-db
  namespace: database-server
spec:
  containers:
  - env:
    - name: MYSQL_ROOT_PASSWORD
      value: "1234"
    image: mariadb:latest
    name: mariadb-db
    ports:
    - containerPort: 3306
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
